{
  "openapi":"3.0.2",
  "info": {
    "title":"TodoList RESTful API",
    "version":"1.0",
    "description": "OpenAPI for Todolist RESTful API",
    "termsOfService": "https://www.google.com",
    "contact": {
      "name": "Danuartha",
      "email": "danuart21@mail.com",
      "url": "https://www.dandev-portfolio.com"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "url": "https://{environtment}.ecommerceapp.com/api/v1",
      "description": "Todolist RESTful API Server",
      "variables": {
        "environtment": {
          "description": "Server Environtment",
          "default": "dev",
          "enum": [
            "dev",
            "qa",
            "prod"
          ]
        }
      }
    }
  ],
  "paths": {
    "/todo": {
      "get": {
        "tags": ["TodoList"],
        "summary": "Get All TodoList",
        "description": "Get all active todolist by default",
        "parameters": [
          {
            "name": "include_done",
            "in": "query",
            "required": false,
            "description": "Is include done todolist",
            "schema": {
              "type": "boolean",
              "nullable": true,
              "default": false
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema": {
              "type": "string",
              "nullable": true,
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "java": {
                "description": "Example name Java",
                "value": "Java"
              },
              "php": {
                "description": "Example name PHP",
                "value": "PHP"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Example success get all todo",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "priority": {
                        "type": "number",
                        "format": "int32"
                      },
                      "tags": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example success get all todo",
                    "value": [
                      {
                        "id": 1,
                        "name": "Java",
                        "priority": 3,
                        "tags": [
                          "Java",
                          "Programming"
                        ]
                      },
                      {
                        "id": 2,
                        "name": "PHP",
                        "priority": 5,
                        "tags": [
                          "PHP",
                          "Programming"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["TodoList"],
        "summary": "Create new TodoList",
        "description": "Create new todolist to database",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1,
                    "required": true
                  },
                  "priority": {
                    "type": "integer",
                    "format": "int32",
                    "required": true,
                    "default": 1
                  },
                  "tags": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              },
              "examples": {
                "java": {
                  "description": "Example create todolist Java",
                  "value": {
                    "name": "Java",
                    "priority": 2,
                    "tags": [
                      "Java",
                      "Programming"
                    ]
                  }
                },
                "php": {
                  "description": "Example create todolist PHP",
                  "value": {
                    "name": "PHP",
                    "priority": 2,
                    "tags": [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Example success create new todo",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "priority": {
                        "type": "number",
                        "format": "int32"
                      },
                      "tags": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                },
                "examples": {
                  "success": {
                    "description": "Example success create new todo",
                    "value": {
                      "id": 1,
                      "name": "Java",
                      "priority": 3,
                      "tags": [
                        "Java",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/todo/{todoId}": {
      "patch": {
        "tags": ["TodoList"],
        "summary": "Update existing todolist",
        "description": "Update existing todolist in database",
        "parameters": [
          {
            "name": "todoId",
            "in": "path",
            "required": true,
            "description": "Todolist id for updated",
            "schema": {
              "type": "string",
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "java": {
                "description": "Sample todoId Java",
                "value": 1
              },
              "php": {
                "description": "Sample todoId PHP",
                "value": 2
              }
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1,
                    "required": true
                  },
                  "priority": {
                    "type": "integer",
                    "format": "int32",
                    "required": true,
                    "default": 1
                  },
                  "tags": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              },
              "examples": {
                "java": {
                  "description": "Example update todolist Java",
                  "value": {
                    "name": "Java",
                    "priority": 2,
                    "tags": [
                      "Java",
                      "Programming"
                    ]
                  }
                },
                "php": {
                  "description": "Example update todolist PHP",
                  "value": {
                    "name": "PHP",
                    "priority": 2,
                    "tags": [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Example success update existing todo",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "priority": {
                        "type": "number",
                        "format": "int32"
                      },
                      "tags": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                },
                "examples": {
                  "success": {
                    "description": "Example success update existing todo",
                    "value": {
                      "id": 1,
                      "name": "Java",
                      "priority": 3,
                      "tags": [
                        "Java",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["TodoList"],
        "summary": "Delete existing TodoList",
        "description": "Delete existing todolist in database",
        "parameters": [
          {
            "name": "todoId",
            "in": "path",
            "required": true,
            "description": "Todolist id for deleted",
            "schema": {
              "type": "string",
              "minLength": 1,
              "maxLength": 100
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Example success delete existing todo",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                    "properties": {
                      "status": {
                        "type": "boolean"
                      }
                    }
                },
                "examples": {
                  "success": {
                    "description": "Example success delete existing todo",
                    "value": {
                      "status": true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Failed delete not found todo",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                    "properties": {
                      "success": {
                        "type": "boolean"
                      }
                    }
                },
                "examples": {
                  "error": {
                    "description": "Failed delete existing todo",
                    "value": {
                      "success": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "externalDocs": {
    "description": "External Docs for API Paths",
    "url": "https://www.google.com"
  },
  "components": {
    "parameters": {
      "TodoListId": {
        "name": "todoId",
        "in": "path",
        "required": true,
        "description": "Todolist id for updated",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        },
        "examples": {
          "java": {
            "description": "Sample todoId Java",
            "value": 1
          },
          "php": {
            "description": "Sample todoId PHP",
            "value": 2
          }
        }
      }
    },
    "schemas": {
      "TodoList": {
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "priority": {
              "type": "number",
              "format": "int32"
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "CreateOrUpdateTodoList": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "priority": {
            "type": "number",
            "format": "int32"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "ArrayTodoList": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "priority": {
              "type": "number",
              "format": "int32"
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
    }
  }
}